feat: add breadcrumbs component
freenowtech/wave pull request #353
Opened 2023-08-11 12:44 UTC by div-Leo

**What:**

​
**Why:**

Add new component Breadcrumbs
​
**How:**

Created new component
Added documentation
Wrote tests

**Media:**
![Capture-2023-08-11-144009](https://github.com/freenowtech/wave/assets/12762609/8290e456-336b-475c-9067-f0b21227aac2)

Issue:  #324

2023-08-14 11:41 UTC, nlopin requested changes
We need to add accessibility to the component.

Another question: can we make the clickable area bigger? At the moment only the text is clickable, why not having the whole block clickable? I think it can be achieved by wrapping the `li` with `a`.

Now:
![CleanShot 2023-08-14 at 13 38 03@2x](https://github.com/freenowtech/wave/assets/1469636/1f47acae-bfb9-4c80-9aa5-6fc7ae70641f)

Ideally:
![CleanShot 2023-08-14 at 13 39 16@2x](https://github.com/freenowtech/wave/assets/1469636/e6ae903f-57e1-4f46-83f2-82c0ba089c05)

2023-08-14 11:41 UTC, nlopin commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +    return (
It is recommended to have the breadcrumb wrapped with the `nav` tag for a11y. 
I found a very good example on the [a11y style guide website](https://a11y-style-guide.com/style-guide/section-navigation.html#kssref-navigation-breadcrumbs) we can use as a markup example.

- [ ] follow the a11y recommendations

2023-08-14 11:41 UTC, nlopin commented on src/components/Breadcrumbs/docs/Breadcrumbs.storybook.mdx
How do we use `Breadcrumbs` with the react-router or next links? Let's show them examples

2023-08-16 07:21 UTC, div-Leo commented on src/components/Breadcrumbs/docs/Breadcrumbs.storybook.mdx
We already have an example of how to use it with react-router, is that enough or do we want to add also Next Links?

2023-08-17 08:08 UTC, div-Leo commented
@nlopin I couldn't wrap the `li` with the `a` because of the structure I chose, it was easier to use padding to increase the area, and the result should be okay.

<img width="150" alt="Screenshot 2023-08-17 at 10 07 21" src="https://github.com/freenowtech/wave/assets/12762609/5ccc6dc5-ef5a-498b-9b65-6b1dc7ed8ee8">

2023-08-17 19:34 UTC, nlopin commented on src/components/Breadcrumbs/docs/Breadcrumbs.storybook.mdx
I missed that, sorry

2023-08-17 19:35 UTC, nlopin approved these changes

2023-08-18 12:25 UTC, merged